-- =============================================================================
-- MODO INVENTARIO DO ALMOXARIFADO (1/3): tabelas
--
-- Pedido do dono (05/10/2026): durante o inventario o sistema segura os pedidos
-- do almoxarifado, a equipe conta item a item (varias linhas por item: quantidade,
-- lote, validade) e, ao fechar, o saldo e ajustado pela diferenca, com relatorio
-- valorizado pelo ultimo preco de compra. Tudo que e decisao vira OPCAO escolhida
-- por quem abre o inventario (bloqueio, liberacao urgente, itens nao contados).
--
-- Escopo: SO o almoxarifado central (warehouse_items.current_stock + lotes do
-- local ALMOX). Farmacia e Satelite Terreo (item_stocks) ficam de fora.
--
-- Escrita so pelas RPCs (migration 20261005120100); o navegador so le.
-- =============================================================================

create table if not exists public.almox_inventarios (
  id uuid primary key default gen_random_uuid(),
  numero integer generated by default as identity,
  status text not null default 'aberto'
    check (status in ('aberto', 'fechado', 'cancelado')),
  aberto_por uuid not null references public.users(id),
  aberto_em timestamptz not null default now(),
  fechado_por uuid references public.users(id),
  fechado_em timestamptz,
  cancelado_por uuid references public.users(id),
  cancelado_em timestamptz,
  motivo_cancelamento text,
  -- OPCOES escolhidas na abertura
  -- todos = nenhum pedido novo e nenhuma saida (entrega de pedido, saida direta,
  --         saida em lote, vencimento, emprestimo) ate o fechamento;
  -- novos = so a criacao de pedido novo fica bloqueada.
  bloqueio text not null check (bloqueio in ('todos', 'novos')),
  permite_liberacao_urgente boolean not null default false,
  -- manter = item nao contado fica com o saldo do sistema; zerar = vira 0.
  nao_contados text not null check (nao_contados in ('manter', 'zerar')),
  observacao text,
  resumo jsonb
);

comment on table public.almox_inventarios is
  'Inventarios do almoxarifado central. So um aberto por vez. Escrita so pelas RPCs almox_inventario_*.';

-- So UM inventario aberto por vez.
create unique index if not exists almox_inventarios_um_aberto
  on public.almox_inventarios ((true)) where status = 'aberto';

create table if not exists public.almox_inventario_contagens (
  id uuid primary key default gen_random_uuid(),
  inventario_id uuid not null references public.almox_inventarios(id) on delete cascade,
  item_id uuid not null references public.warehouse_items(id),
  lote text,
  validade date,
  quantidade integer not null check (quantidade >= 0),
  -- current_stock do item no instante em que a contagem DO ITEM foi salva.
  -- No fechamento: diferenca = contado - este valor, aplicada sobre o saldo
  -- atual (entradas/saidas feitas depois da contagem continuam valendo).
  saldo_sistema_no_momento integer not null,
  contado_por uuid not null references public.users(id),
  contado_em timestamptz not null default now()
);

create index if not exists almox_inventario_contagens_inv_item
  on public.almox_inventario_contagens (inventario_id, item_id);

create table if not exists public.almox_inventario_liberacoes (
  id uuid primary key default gen_random_uuid(),
  inventario_id uuid not null references public.almox_inventarios(id) on delete cascade,
  request_id uuid not null references public.requests(id),
  liberado_por uuid not null references public.users(id),
  liberado_em timestamptz not null default now(),
  motivo text not null check (length(btrim(motivo)) >= 5),
  unique (inventario_id, request_id)
);

-- Fotografia por item gravada no FECHAMENTO (o relatorio nao muda depois,
-- mesmo que preco/saldo do item mudem).
create table if not exists public.almox_inventario_resultado (
  inventario_id uuid not null references public.almox_inventarios(id) on delete cascade,
  item_id uuid not null references public.warehouse_items(id),
  item_nome text,
  item_codigo text,
  unidade text,
  contado boolean not null,
  quantidade_contada integer,
  saldo_sistema_contagem integer,
  saldo_antes integer not null,
  diferenca integer not null,
  saldo_depois integer not null,
  valor_unitario numeric not null default 0,
  valor_diferenca numeric not null default 0,
  valor_final numeric not null default 0,
  lotes jsonb,
  primary key (inventario_id, item_id)
);

alter table public.almox_inventarios enable row level security;
alter table public.almox_inventario_contagens enable row level security;
alter table public.almox_inventario_liberacoes enable row level security;
alter table public.almox_inventario_resultado enable row level security;

-- Leitura: quem opera o almoxarifado (atendente/gestor do almox) e o admin.
drop policy if exists almox_inventarios_select on public.almox_inventarios;
create policy almox_inventarios_select on public.almox_inventarios
  for select to authenticated using (public.fn_user_pode_modulo('almox'));
drop policy if exists almox_inventario_contagens_select on public.almox_inventario_contagens;
create policy almox_inventario_contagens_select on public.almox_inventario_contagens
  for select to authenticated using (public.fn_user_pode_modulo('almox'));
drop policy if exists almox_inventario_liberacoes_select on public.almox_inventario_liberacoes;
create policy almox_inventario_liberacoes_select on public.almox_inventario_liberacoes
  for select to authenticated using (public.fn_user_pode_modulo('almox'));
drop policy if exists almox_inventario_resultado_select on public.almox_inventario_resultado;
create policy almox_inventario_resultado_select on public.almox_inventario_resultado
  for select to authenticated using (public.fn_user_pode_modulo('almox'));

-- Escrita nenhuma pelo navegador (sem policy de escrita e sem privilegio).
revoke all on public.almox_inventarios, public.almox_inventario_contagens,
  public.almox_inventario_liberacoes, public.almox_inventario_resultado from anon, authenticated;
grant select on public.almox_inventarios, public.almox_inventario_contagens,
  public.almox_inventario_liberacoes, public.almox_inventario_resultado to authenticated;
